service: serverless-template

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-iam-roles-per-function
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment:
    productsTabledynamodb: ${self:service}-products

package:
  exclude:
    - .serverless/**
    - .git/**
    - node_modules/**


functions:
  - ${file(sls/functions/newProduct.yml)}

resources:
  # Created resource dynamoDb in yml code
  - ${file(sls/resources/productsTable.yml)}